import { BioModal } from "../components/BioModal";
import { Arrow, Shell } from "../components/SiteChrome";
import { pageMetadata } from "../lib/seo";

type Person = { name: string; role: string; image?: string; bio?: string[] };

const paragBio = [
  "Parag is a serial entrepreneur with a track record of commercializing novel chemistry-based innovations. He has a strong background in biotechnology, organic, macromolecular, and biochemistry, and material science. His experience encompasses product R&D, global business development, manufacturing, and capitalization of companies through public and private financing.",
  "He received his PhD in Chemistry from Rensselaer Polytechnic Institute, Troy, NY, and MSc in Chemistry from the Indian Institute of Technology, Mumbai, India."
];

const davidBio = [
  "David brings broad business experience as a finance professional and entrepreneur/operator. Since 2012, David has served as Chairman and Chief Executive Officer of Boston Harbor, a financial industry asset management strategy platform. His track record spans the founding of two start-ups, two leveraged buyouts, and the management and sale of Tribotek to Methode Electronics.",
  "David holds a BS in Electrical Engineering from Cornell University and an MBA from Harvard University."
];

const executives: Person[] = [
  { name:"Parag G. Mehta, PhD", role:"Chief Executive Officer", image:"/assets/people/parag-mehta.jpg", bio:paragBio },
  { name:"Selda Samakoglu, MD, PhD", role:"Chief Medical Officer", image:"/assets/people/selda-samakoglu.jpg", bio:["Selda is a distinguished medical oncologist, physician-scientist, and biopharmaceutical executive with over 20 years of experience spanning academia, clinical medicine, and industry. Most recently, she served as Vice President of Clinical Sciences at Iovance Biotherapeutics, where she led global development of cell-based therapies for hematologic malignancies and solid tumors, including non-small cell lung cancer and head and neck cancer. She has also held executive leadership roles at ImClone Systems, Gilead Sciences, Bristol Myers Squibb, CSL Behring, Boehringer Ingelheim, and Replimune.","Over her career, she has successfully led programs from IND through proof-of-concept to NDA/BLA approvals across monoclonal antibodies, small molecules, oncolytic viruses, and cell-based immunotherapies. She played pivotal roles in the regulatory approvals of Cetuximab, Imbruvica, Elotuzumab, and Amtagvi and has engaged with global health authorities including the FDA, EMA, CDE, and MHRA.","Dr. Samakoglu earned her BS and MD from Hacettepe University School of Medicine in Turkey, followed by specialization in Pediatric Hematology/Oncology at Hacettepe and Mount Sinai School of Medicine. She holds a PhD in Medical Biology and Human Genetics and completed postdoctoral clinical and research fellowships at Institut Pasteur and Memorial Sloan Kettering Cancer Center."] },
  { name:"Luis Z. Avila, PhD", role:"Chief Scientific Officer", image:"/assets/people/luis-avila.png", bio:["Luis brings to Aveta Biomics more than 20 years of industrial experience spanning early startup, biotech, and multinational pharmaceutical companies. He has successfully guided product concepts through discovery, optimization, product development, and CMC for clinical evaluation or product launch, both internally and with external collaborators.","He obtained his PhD in Bioorganic Chemistry from Stanford University and was a Postdoctoral Fellow at Harvard University in the Department of Chemistry and Chemical Biology. He holds more than twenty issued U.S. patents and coauthored more than twenty scientific articles and book chapters."] },
  { name:"David Page", role:"Chief Financial Officer", image:"/assets/people/david-page.jpg", bio:davidBio },
  { name:"Robert Charnas, PhD", role:"Senior Vice President, Regulatory Affairs", image:"/assets/people/robert-charnas.jpg", bio:["Robert is a pharmaceutical executive with over 20 years of global regulatory and strategic program leadership experience. He has a proven track record in successful product registrations for small and large molecules across North America, Europe, and Asia, with expertise spanning development from pre-IND through Phase IV studies.","He most recently served as Worldwide Regulatory Affairs Transformation Lead and Head of U.S. Regulatory Affairs at Servier Bio-Innovation. Previously, he was Vice President and Head of Global Regulatory Affairs at Agios Pharmaceuticals and Vice President of Strategic Program Direction for Oncology at Regeneron Pharmaceuticals. He also held roles at Amgen, Novartis, and Hoffmann-La Roche. He received his PhD from Harvard."] },
  { name:"Kevin Zikaras", role:"Vice President, Clinical Operations and Development", image:"/assets/people/kevin-zikaras.png", bio:["Kevin has over 14 years of experience in oncology clinical development spanning academic cancer centers, biotechnology companies, and global pharmaceutical organizations. His expertise includes clinical operations, clinical supply, data management, pharmacovigilance, quality systems, and execution of global oncology trials from early-stage development through pivotal Phase 3 studies.","Most recently, Kevin served as Vice President of Clinical Development Operations at Convergent Therapeutics. Previously, at TCR² Therapeutics, he built and led clinical operations, clinical supply, data management, and pharmacovigilance functions. Earlier, at Actinium Pharmaceuticals, he served as program lead for the pivotal Phase 3 SIERRA trial. He also managed global immuno-oncology studies at Bristol Myers Squibb and held clinical research leadership positions at Memorial Sloan Kettering Cancer Center and Columbia University Medical Center.","Kevin earned an MBA from Cornell University, an MS in Healthcare Leadership from Weill Cornell Graduate School of Medical Sciences, and an MS in Regulatory Affairs from Northeastern University."] },
  { name:"Murat Budak, MD, PhD", role:"Medical Director", image:"/assets/people/murat-budak.jpg", bio:["Dr. Budak brings over 20 years of experience at the intersection of oncology, translational science, and clinical research. A physician-scientist trained in both medicine and physiology, he has served as principal investigator for oncology trials, including a Phase 2 study evaluating pembrolizumab in combination with a personalized cancer vaccine in non-small cell lung cancer.","Before joining Aveta, Dr. Budak was an Associate Professor at Hacettepe University Medical School, where he led translational oncology research and contributed to patient care within the Lung Cancer Center. He previously held research leadership roles at the University of Pennsylvania and the Philadelphia VA Medical Center.","Dr. Budak earned his MD from Hacettepe University and his PhD in Physiology from Gazi University. He completed postdoctoral research fellowships at Mount Sinai School of Medicine and the University of Pennsylvania."] },
];

const directors: Person[] = [
  { name:"Parag G. Mehta, PhD", role:"Board Director", image:"/assets/people/parag-mehta.jpg", bio:paragBio },
  { name:"Peter Dolan", role:"Board Director", image:"/assets/people/peter-dolan.jpg", bio:["As the former CEO and Chairman of Bristol-Myers Squibb, Mr. Dolan has an impressive track record of leadership in the pharmaceutical industry. His 18 transformative years at BMS included the addition of Eliquis to its portfolio, investment in ImClone’s Erbitux, licensing of Yervoy, and substantial investments in biologics.","Post-BMS, Mr. Dolan led GeminX to a $225 million acquisition by Cephalon Pharmaceuticals. He served as Chairman of the Board of Trustees at Tufts University and chairs the Partnership for A Healthier America. He holds a BA magna cum laude from Tufts University and an MBA from Dartmouth’s Tuck School of Business."] },
  { name:"Bharat Tewarie, MD, MBA", role:"Board Director", image:"/assets/people/bharat-tewarie.jpg", bio:["Bharat Tewarie is currently the CEO of Helio Genomics, a cancer diagnostics company. He brings deep strategic and operational expertise to the Aveta Biomics board. Trained as a medical doctor with an MBA, Dr. Tewarie held positions of increasing responsibility at Boehringer Ingelheim, Roche, Merck Serono, and UCB in Europe and the USA.","Most recently, he was Executive Vice President and Chief Marketing Officer and a member of the Executive Committee of UCB. Since 2021 he has been CEO and Chair of the Board of ViroCarb Inc and the founder of Boston Biopharma Consultants. He received his MD from Utrecht University and MBA from Webster University."] },
  { name:"David Page", role:"Board Director", image:"/assets/people/david-page.jpg", bio:davidBio },
  { name:"Thomas Rudolph, MD", role:"Board Director", image:"/assets/people/thomas-rudolph.jpg", bio:["Dr. Thomas Rudolph brings deep expertise in life sciences, pharmaceuticals, and private equity, with a distinguished career spanning more than two decades. Most recently, he was CEO of EHC N.V. and currently holds board and advisory roles in biotechnology and specialty pharma companies.","Before leaving McKinsey & Company as a Senior Partner in 2021, he advised leading pharmaceutical and specialty pharma companies in the U.S. and Europe. He founded the McKinsey Cancer Center and the European Healthcare Transactions team.","Dr. Rudolph holds a Medical Doctor degree from the University of Tuebingen Medical School, where his doctoral research focused on Molecular Biology and Oncology. He also earned a minor in Business Administration from the University of Tuebingen Business School."] },
];

const advisors: Person[] = [
  { name:"Anastasia Tousimis, MD, FACS, MBA", role:"Scientific and Medical Advisor", image:"/assets/people/anastasia-tousimis.jpg", bio:["Dr. Anastasia Tousimis serves as deputy director of Baptist Health Cancer Care, chief of breast surgery at Baptist Health Cancer Care, medical director of the Al and Jane Nahmad Women’s Cancer Center and chief medical liaison of the Memorial Sloan Kettering Cancer Center Alliance. Previously, she served as the Director of the Scully Welsh Cancer Center at Cleveland Clinic Indian River Hospital. She also served as Professor of Surgery and Director of the Breast Center at Georgetown University Hospital, where she led the Division of Breast Surgery and the Clinical Research program.","Dr. Tousimis was an Associate Professor of Surgery at Weill Cornell Medical College. She earned her MD from Albany Medical College and MBA from the Sloan School of Management at MIT. Recognized for her innovations in breast cancer management, she has published extensively and was the 99th President of the American Medical Women’s Association. In 2023, Georgetown University Hospital named an operating room in her honor."] },
  { name:"Sid Puram, MD, PhD", role:"Scientific and Medical Advisor", image:"/assets/people/sid-puram.jpg", bio:["Dr. Sidharth (Sid) V. Puram, MD, PhD, FACS, is the Lindburg Professor and Chair of the Department of Otolaryngology — Head & Neck Surgery at Washington University School of Medicine in St. Louis. He concurrently serves as the Chief of Otolaryngology at Barnes-Jewish Hospital and the Director of the Head and Neck Tumor Center at the Siteman Cancer Center. As a nationally recognized physician-scientist and Key Opinion Leader (KOL), Dr. Puram specializes in head and neck surgical oncology and microvascular reconstructive surgery. His clinical expertise centers on the comprehensive treatment of advanced head and neck cancers, including squamous cell carcinoma, salivary gland tumors, and thyroid malignancies.","In addition to his surgical practice, Dr. Puram leads pioneering translational research that applies single-cell genomics to map intra-tumoral heterogeneity and identify the mechanisms driving tumor metastasis and treatment resistance. His academic pedigree includes a Bachelor of Science in Biology and Neuroscience from the Massachusetts Institute of Technology (MIT), followed by a combined MD/PhD in Neurobiology from Harvard Medical School. He completed his residency training within the Harvard Combined Program at Massachusetts Eye and Ear, and a specialized fellowship in Head and Neck Surgical Oncology at the Ohio State University's James Cancer Center. Dr. Puram’s profound contributions to biomedical research have earned him numerous accolades, including his prestigious election into the American Society for Clinical Investigation (ASCI)."] },
  { name:"Andrew Sikora, MD, PhD", role:"Scientific and Medical Advisor", image:"/assets/people/andrew-sikora.jpg", bio:["Dr. Andrew Sikora is a renowned head and neck cancer surgeon, tumor immunologist, and professor of Head and Neck Surgery and Immunology at The University of Texas MD Anderson Cancer Center. His clinical expertise includes oropharyngeal and HPV-related head and neck cancers and oral premalignancy. His research focuses on understanding and reversing cancer-mediated immunosuppression through innovative tumor models and biospecimen analysis.","Dr. Sikora holds an MD and PhD in Microbiology and Immunology from Albert Einstein College of Medicine. He completed his undergraduate studies at Yale University, postgraduate training in General Surgery and Otolaryngology at New York University School of Medicine, and a fellowship in Head and Neck Surgical Oncology at MD Anderson."] },
  { name:"Jonathan Schoenfeld, MD, MPH", role:"Scientific and Medical Advisor", image:"/assets/people/jonathan-schoenfeld.jpg", bio:["Dr. Jonathan Schoenfeld is a Professor of Radiation Oncology at Harvard Medical School and an MGB Endowed Cancer Chair. He serves as Director of Head and Neck, Cutaneous, and Melanoma Radiation Oncology at Dana-Farber Brigham Cancer Center, Senior Physician at Dana-Farber Cancer Institute, and Associate Director of Clinical Research in the Department of Radiation Oncology.","Dr. Schoenfeld’s research focuses on clinical, epidemiologic, and translational studies in head and neck and skin cancers, including the immunologic effects of radiation therapy and studies combining radiation with novel oncology agents.","Dr. Schoenfeld earned his medical degree from Harvard Medical School following a research fellowship as a Gates Scholar at the University of Cambridge. He completed his medical internship at Memorial Sloan Kettering Cancer Center and residency in the Harvard Radiation Oncology Program. He also holds an MPH in Clinical Effectiveness from the Harvard T.H. Chan School of Public Health."] },
  { name:"Daniel L. Hartl, PhD", role:"Scientific Advisor", image:"/assets/people/daniel-hartl.jpg", bio:["Daniel is Higgins Professor of Biology and former Chair of the Department of Organismic and Evolutionary Biology at Harvard University. His laboratory studies genetics, genomics and molecular evolution. His seminal contributions to experimental evolutionary genetics have far-reaching impact on understanding the development of resistance to drugs in human diseases.","An elected member of the National Academy of Sciences, the American Academy of Arts and Sciences, and the National Academy of Sciences of India, Prof. Hartl has authored or coauthored more than 400 scientific articles and 20 books."] },
  { name:"Eugene I. Shakhnovich, PhD", role:"Scientific Advisor", image:"/assets/people/eugene-shakhnovich.jpg", bio:["Eugene is a Professor of Chemistry and Chemical Biology at Harvard University. He is a leading researcher in protein folding and has carried out crucial work tying the physical chemistry of proteins to evolutionary biology. His laboratory has made fundamental contributions to understanding mechanisms of drug resistance by studying mutational fitness and organismal evolution using biophysical principles.","He is the author of more than 200 publications and co-founded Vitae Pharmaceuticals, which was acquired by Allergan for $639 million."] },
  { name:"Ajay Gupta", role:"Executive Advisor", image:"/assets/people/ajay-gupta.jpg", bio:["Ajay Gupta, Senior Partner Emeritus at McKinsey & Company, brings over 30 years of healthcare expertise spanning pharmaceuticals, biotech, medtech, health systems, academic centers, and healthcare services. At McKinsey, he led the Midwest Healthcare and North America Medical Products practices, advising on strategy, growth, M&A, and innovation.","Gupta serves on multiple boards and is an active investor focused on growth companies and innovation. He holds an MBA from Stanford, where he was an Arjay Miller Scholar, and a B.Tech from IIT Delhi, where he received the President’s Gold Medal."] },
  { name:"Jan Hagemeier", role:"Executive Advisor", image:"/assets/people/jan-hagemeier.jpg", bio:["Jan Hagemeier is a seasoned financial executive with three decades of experience in global equity capital markets, investor engagement, and institutional fundraising. Previously, Jan served as CEO and Head of Sales at Sanford C. Bernstein Ltd in the UK and as Partner at AllianceBernstein in New York. He also held senior management roles at Deutsche Bank.","As an Executive Advisor, Jan provides strategic financial guidance, drawing on his experience in IPOs, secondary offerings, and debt financing, where he helped raise several billion dollars. His understanding of investor expectations and market positioning supports Aveta’s financing strategy and investor relations."] },
];

function People({ people, section }: { people: Person[]; section: string }) {
  return <div className="people-grid people-portraits">{people.map(person => <BioModal key={person.name} {...person} section={section} />)}</div>;
}

export const metadata = pageMetadata({
  title: "About Aveta Biomics",
  description:
    "A clinical-stage biotechnology company advancing oral immunotherapies, led by an experienced team in oncology, drug development and translational science.",
  path: "/about",
});

export default function AboutPage(){return <Shell active="/about"><main>
  <section className="about-approved-hero container"><div><p className="eyebrow">ABOUT AVETA BIOMICS</p><h1>Built to <span className="accent">extend the reach</span><br />of immunotherapy.</h1><p className="lead">Aveta Biomics is a clinical-stage biotechnology company developing oral immunotherapies designed to extend the reach of immunotherapy across immune-cold and immune-hot tumors.</p><div className="actions"><a className="button" href="/science">Explore Our Science <Arrow /></a><a className="button-outline" href="#leadership">Meet Our Leadership <Arrow /></a></div></div><aside><p className="eyebrow">AVETA AT A GLANCE</p><div className="glance orange-line"><small>WHAT WE DEVELOP</small><strong>ORAL IMMUNOTHERAPIES FOR HARD-TO-TREAT CANCERS</strong></div><div className="glance green-line"><small>WHAT THEY DO</small><strong>CHANGE THE TUMOR IMMUNE MICROENVIRONMENT (TIME)</strong></div><div className="glance purple-line"><small>WHERE WE ARE</small><strong>PHASE 3, PHASE 2 AND PRECLINICAL PROGRAMS</strong></div></aside></section>
  <section className="section-sm soft-bg"><div className="container"><p className="eyebrow center">WHAT AVETA DOES</p><h2 className="center">Many oncology drugs are built around a target.<br />Aveta is built around the tumor ecosystem.</h2><div className="about-process"><article><b>01</b><span className="process-icon orange-border">◉</span><h3>ORAL THERAPY</h3><p>Designed around the body’s own immune regulation</p></article><i><Arrow /></i><article><b>02</b><span className="process-icon purple-border">✹</span><h3>REPROGRAM THE TUMOR ENVIRONMENT</h3><p>Counter immune suppression upstream of checkpoints</p></article><i><Arrow /></i><article><b>03</b><span className="process-icon green-border">✣</span><h3>COORDINATED ANTITUMOR IMMUNE RESPONSE</h3><p>Enable immune activity across cold and hot tumors</p></article></div></div></section>
  <section className="about-why"><div className="container split"><div><p className="eyebrow">WHY THIS WORK MATTERS</p><h2>The measure of progress is<br />what treatment allows people to keep.</h2><p className="body-copy">Cancer such as Head and neck cancer can affect the most human parts of daily life. Speaking, eating, smiling and connecting with others. That human reality remains at the center of why we do this work and our treatment is intended to not only treat active cancer and increase the lifespan but also preserve these most basic human needs and improve patients&apos; health span.</p></div><div className="about-why-media"><img src="/assets/about-approved-patients.jpg" width={1400} height={750} alt="A head and neck cancer patient talking with a family member" /></div></div></section>
  <section id="leadership" className="section-sm"><div className="container"><p className="eyebrow">EXECUTIVE LEADERSHIP</p><People people={executives} section="EXECUTIVE LEADERSHIP" /></div></section>
  <section className="section-sm soft-bg"><div className="container"><p className="eyebrow">BOARD OF DIRECTORS</p><People people={directors} section="BOARD OF DIRECTORS" /></div></section>
  <section className="section-sm"><div className="container"><p className="eyebrow">THE BOARD OF ADVISORS</p><People people={advisors} section="THE BOARD OF ADVISORS" /></div></section>
  <section className="about-execution navy-bg"><div className="container"><h2>Science-led. Clinically focused. Built to execute.</h2><div><span>TRANSLATIONAL SCIENCE</span><span>GLOBAL CLINICAL DEVELOPMENT</span><span>REGULATORY &amp; MANUFACTURING READINESS</span></div></div></section>
  <section className="section-sm"><div className="container final-cta"><h2>Writing the next chapter of immuno-oncology</h2><div><p>We welcome conversations with those who share our ambition to extend the reach of immunotherapy.</p><div className="actions"><a className="button" href="mailto:betterhealth@avetabiomics.com?subject=Partnership inquiry">Partner With Us <Arrow /></a></div></div></div></section>
</main></Shell>}
