import { Arrow, Shell } from "../components/SiteChrome";
import { pageMetadata } from "../lib/seo";

export const metadata = pageMetadata({
  title: "Expanded Access Policy",
  description:
    "Aveta's policy on physician requests for expanded access to APG-157 for patients with serious or life-threatening cancer who cannot join a clinical trial.",
  path: "/expanded-access",
});

export default function ExpandedAccessPage(){return <Shell active="/expanded-access"><main>
  <section className="photo-hero expanded-access-hero"><picture>
    {/* Desktop artwork has a white gradient baked into its left 44%, which the
        overlaid copy sits on. Stacked layouts put the copy below the photo, so
        they get the ungraded original — the baked fade would otherwise read as
        a washed-out band across the image. */}
    <source media="(max-width: 860px)" srcSet="/assets/expanded-access-hero-mobile.jpg" />
    <img className="photo" src="/assets/expanded-access-hero.jpg" width={2400} height={803} alt="A patient and family member speaking with a physician" />
  </picture><div className="photo-hero-copy"><p className="eyebrow">EXPANDED ACCESS</p><h1>A thoughtful pathway when clinical trials are not an option.</h1><p className="lead">Aveta evaluates physician requests for access to APG-157 in limited circumstances for patients with serious or life-threatening cancer.</p></div></section>
  <section className="section"><div className="policy-wrap container"><h2>Aveta Biomics Expanded Access Policy</h2><p className="body-copy">Clinical trials remain the primary pathway for access to APG-157 and are essential to establishing its safety and efficacy. We recognize, however, that some patients with serious or life-threatening cancer may be unable to participate in a clinical trial. In limited circumstances, Aveta may consider physician requests for expanded access in accordance with applicable laws and FDA requirements.</p><div className="notice"><strong>APG-157 is an investigational product and has not been approved by the FDA or any other regulatory authority. Its safety and efficacy have not been established.</strong></div></div></section>
  <section className="section-sm"><div className="policy-wrap container split"><div><h3>What is expanded access?</h3><p className="body-copy">Expanded access, sometimes called compassionate use, allows an eligible patient to receive an investigational therapy outside a clinical trial when no comparable or satisfactory treatment option is available.</p></div><div><h3>Who may be considered</h3><ul className="criteria-list"><li>Serious or life-threatening cancer</li><li>No comparable or satisfactory treatment option</li><li>Unable to participate in an APG-157 clinical trial</li><li>Potential benefit justifies the potential risks</li><li>Access would not compromise clinical trials or development</li></ul></div></div></section>
  <section className="section-sm"><div className="policy-wrap container policy-card"><h3>Criteria for APG-157</h3><p className="body-copy">Requests may be considered for patients with head and neck cancer or, case by case, another life-threatening cancer when adequate clinical evidence supports potential use. The treating physician must determine that the potential benefit outweighs the risks, and sufficient drug supply and clinical support must be available.</p></div></section>
  <section className="section soft-bg"><div className="container"><p className="eyebrow">FOR TREATING PHYSICIANS</p><h2>How to request expanded access</h2><div className="steps"><article className="step"><b>1</b><h3>Submit a physician request</h3><p>Email <a className="text-link" href="mailto:betterhealth@avetabiomics.com">betterhealth@avetabiomics.com</a> with the patient’s diagnosis, treatment history, clinical status and medical rationale.</p></article><article className="step"><b>2</b><h3>Aveta acknowledges receipt</h3><p>Aveta will acknowledge a complete request within five business days and begin medical, scientific and supply review.</p></article><article className="step"><b>3</b><h3>Obtain required approvals</h3><p>If Aveta agrees to provide APG-157, the treating physician is responsible for FDA authorization and applicable Institutional Review Board approval.</p></article><article className="step"><b>4</b><h3>Consent and oversight</h3><p>The treating physician must obtain informed consent, administer treatment, monitor the patient and complete required safety reporting.</p></article></div></div></section>
  <section className="section-sm"><div className="container policy-mini"><article className="card"><h3>Cost</h3><p>Aveta will not charge for APG-157 supplied through expanded access. Shipping and handling costs may be charged. The patient, physician, institution or insurer may be responsible for administration, medical care and monitoring costs.</p></article><article className="card"><h3>Availability</h3><p>Access depends on adequate drug supply and Aveta’s ability to support treatment without affecting ongoing clinical trials or development.</p></article><article className="card"><h3>Important limitations</h3><p>Not every request can be accommodated. Insufficient evidence, limited supply, patient safety concerns or potential interference with development may result in a request being declined.</p></article></div></section>
  <section className="section-sm"><div className="container contact-band navy-bg"><div><p className="eyebrow" style={{color:'#9ec0ff'}}>EXPANDED ACCESS CONTACT</p><h2>Requests must be submitted by the patient’s treating physician.</h2><p>Posting this policy does not guarantee that expanded access will be provided.</p></div><a className="button-outline" href="mailto:betterhealth@avetabiomics.com">betterhealth@avetabiomics.com <Arrow /></a></div></section>
</main></Shell>}
